# From the NumPy Doucmentation

https://numpy.org/doc/stable/user/quickstart.html

***

In [1]:
import numpy as np

In [19]:
 list(range(1,10,2)) #Cant take float numbers only ints 

[1, 3, 5, 7, 9]

In [11]:
x = np.arange(1.5, 10.1, 0.2) #Can take float numbers

In [12]:
x.dtype #cant do this with liist

dtype('float64')

In [20]:
x

array([1.5, 1.7, 1.9, 2.1, 2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9,
       4.1, 4.3, 4.5, 4.7, 4.9, 5.1, 5.3, 5.5, 5.7, 5.9, 6.1, 6.3, 6.5,
       6.7, 6.9, 7.1, 7.3, 7.5, 7.7, 7.9, 8.1, 8.3, 8.5, 8.7, 8.9, 9.1,
       9.3, 9.5, 9.7, 9.9])

In [21]:
x.shape

(43,)

In [4]:
s = np.arange(15).reshape(3,5) #reshapes into 3 rows and 5 colums

In [5]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
s.shape

(3, 5)

In [23]:
x.shape

(43,)

In [27]:
x.reshape(-1, 43) #-1 means for numpy to figure it out

array([[1.5, 1.7, 1.9, 2.1, 2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9,
        4.1, 4.3, 4.5, 4.7, 4.9, 5.1, 5.3, 5.5, 5.7, 5.9, 6.1, 6.3, 6.5,
        6.7, 6.9, 7.1, 7.3, 7.5, 7.7, 7.9, 8.1, 8.3, 8.5, 8.7, 8.9, 9.1,
        9.3, 9.5, 9.7, 9.9]])

In [29]:
x = np.arange(0.0, 10.0, 0.01)
x

In [32]:
y = x ** 2
y

array([0.00000e+00, 1.00000e-04, 4.00000e-04, 9.00000e-04, 1.60000e-03,
       2.50000e-03, 3.60000e-03, 4.90000e-03, 6.40000e-03, 8.10000e-03,
       1.00000e-02, 1.21000e-02, 1.44000e-02, 1.69000e-02, 1.96000e-02,
       2.25000e-02, 2.56000e-02, 2.89000e-02, 3.24000e-02, 3.61000e-02,
       4.00000e-02, 4.41000e-02, 4.84000e-02, 5.29000e-02, 5.76000e-02,
       6.25000e-02, 6.76000e-02, 7.29000e-02, 7.84000e-02, 8.41000e-02,
       9.00000e-02, 9.61000e-02, 1.02400e-01, 1.08900e-01, 1.15600e-01,
       1.22500e-01, 1.29600e-01, 1.36900e-01, 1.44400e-01, 1.52100e-01,
       1.60000e-01, 1.68100e-01, 1.76400e-01, 1.84900e-01, 1.93600e-01,
       2.02500e-01, 2.11600e-01, 2.20900e-01, 2.30400e-01, 2.40100e-01,
       2.50000e-01, 2.60100e-01, 2.70400e-01, 2.80900e-01, 2.91600e-01,
       3.02500e-01, 3.13600e-01, 3.24900e-01, 3.36400e-01, 3.48100e-01,
       3.60000e-01, 3.72100e-01, 3.84400e-01, 3.96900e-01, 4.09600e-01,
       4.22500e-01, 4.35600e-01, 4.48900e-01, 4.62400e-01, 4.761

In [34]:
np.linspace(0.0, 10.0, 101) #Takes a max and min and the number of points you
                            #Want between them

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [35]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
I.dtype

dtype('float64')

In [41]:
I.astype('int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [44]:
I[:, 2]

array([0., 0., 1.])

***
## End